#!/bin/bash
# claude-harness — snapshot session context before context window compression
# PreCompact hook — always exits 0, never blocks compaction

REPO_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
TIMESTAMP=$(date +"%Y-%m-%dT%H-%M")

SESSIONS_DIR="$REPO_DIR/project/sessions"
if [ -f "$REPO_DIR/harness-config.json" ] && command -v node > /dev/null 2>&1; then
  TICKET_DIR=$(node -e "
    const c = JSON.parse(require('fs').readFileSync('$REPO_DIR/harness-config.json','utf8'));
    process.stdout.write(c.tickets?.directory || 'project/tickets');
  " 2>/dev/null)
  SESSIONS_DIR="$REPO_DIR/$(dirname "$TICKET_DIR")/sessions"
fi

BACKUP_FILE="$SESSIONS_DIR/compaction-$TIMESTAMP.md"

if [ ! -d "$SESSIONS_DIR" ]; then
  exit 0
fi

BRANCH=$(git -C "$REPO_DIR" branch --show-current 2>/dev/null || echo "unknown")
VERSION="unknown"
if [ -f "$REPO_DIR/.claude/.harness-version" ]; then
  VERSION=$(cat "$REPO_DIR/.claude/.harness-version" 2>/dev/null || echo "unknown")
fi
LAST_COMMITS=$(git -C "$REPO_DIR" log --oneline -5 2>/dev/null || echo "none")
UNCOMMITTED=$(git -C "$REPO_DIR" diff --name-only 2>/dev/null)
STAGED=$(git -C "$REPO_DIR" diff --cached --name-only 2>/dev/null)

cat > "$BACKUP_FILE" << EOF
# Compaction Snapshot — $TIMESTAMP

> Auto-generated by PreCompact hook. Context window was about to compress.

| Field | Value |
|-------|-------|
| **Timestamp** | $TIMESTAMP |
| **Branch** | $BRANCH |
| **Version** | $VERSION |

## Last 5 Commits

\`\`\`
$LAST_COMMITS
\`\`\`

## Uncommitted Changes

\`\`\`
${UNCOMMITTED:-none}
\`\`\`

## Staged Changes

\`\`\`
${STAGED:-none}
\`\`\`
EOF

echo "" >&2
echo "============================================" >&2
echo "  COMPACTION SNAPSHOT SAVED" >&2
echo "============================================" >&2
echo "  Saved to: $(basename "$SESSIONS_DIR")/compaction-$TIMESTAMP.md" >&2
echo "  Branch: $BRANCH | Version: $VERSION" >&2
echo "============================================" >&2
echo "" >&2

exit 0
