#!/bin/bash
# claude-harness — snapshot session context before context window compression
# PreCompact hook — always exits 0, never blocks compaction
# Reads ticket directory from harness-config.json, falls back to project/sessions/

REPO_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
TIMESTAMP=$(date +"%Y-%m-%dT%H-%M")

# Determine sessions directory from config or default
SESSIONS_DIR="$REPO_DIR/project/sessions"
NODE_BIN="node"
if ! command -v node > /dev/null 2>&1; then
  [ -x "$HOME/.local/node/bin/node" ] && NODE_BIN="$HOME/.local/node/bin/node" || NODE_BIN=""
fi
if [ -f "$REPO_DIR/harness-config.json" ] && [ -n "$NODE_BIN" ]; then
  TICKET_DIR=$(H_CONFIG="$REPO_DIR/harness-config.json" "$NODE_BIN" -e "
    const c = JSON.parse(require('fs').readFileSync(process.env.H_CONFIG,'utf8'));
    process.stdout.write(c.tickets?.directory || 'project/tickets');
  " 2>/dev/null)
  # Corrupted config → empty TICKET_DIR → dirname "" = "." → wrong dir; fall back
  [ -n "$TICKET_DIR" ] || TICKET_DIR="project/tickets"
  SESSIONS_DIR="$REPO_DIR/$(dirname "$TICKET_DIR")/sessions"
fi

BACKUP_FILE="$SESSIONS_DIR/compaction-$TIMESTAMP.md"

# Ensure sessions directory exists
if [ ! -d "$SESSIONS_DIR" ]; then
  exit 0
fi

# Gather current state
BRANCH=$(git -C "$REPO_DIR" branch --show-current 2>/dev/null || echo "unknown")
VERSION="unknown"
if [ -f "$REPO_DIR/package.json" ]; then
  NODE_BIN="node"
  if ! command -v node > /dev/null 2>&1; then
    [ -x "$HOME/.local/node/bin/node" ] && NODE_BIN="$HOME/.local/node/bin/node" || NODE_BIN=""
  fi
  [ -n "$NODE_BIN" ] && VERSION=$(H_PKG="$REPO_DIR/package.json" "$NODE_BIN" -e "console.log(require(process.env.H_PKG).version)" 2>/dev/null || echo "unknown")
fi
LAST_COMMITS=$(git -C "$REPO_DIR" log --oneline -5 2>/dev/null || echo "none")
UNCOMMITTED=$(git -C "$REPO_DIR" diff --name-only 2>/dev/null)
STAGED=$(git -C "$REPO_DIR" diff --cached --name-only 2>/dev/null)

cat > "$BACKUP_FILE" << EOF
# Compaction Snapshot — $TIMESTAMP

> Auto-generated by PreCompact hook. Context window was about to compress.
> Review this file to recover decision context from a prior conversation segment.

| Field | Value |
|-------|-------|
| **Timestamp** | $TIMESTAMP |
| **Branch** | $BRANCH |
| **Version** | $VERSION |

## Last 5 Commits

\`\`\`
$LAST_COMMITS
\`\`\`

## Uncommitted Changes

\`\`\`
${UNCOMMITTED:-none}
\`\`\`

## Staged Changes

\`\`\`
${STAGED:-none}
\`\`\`
EOF

echo "" >&2
echo "============================================" >&2
echo "  COMPACTION SNAPSHOT SAVED" >&2
echo "============================================" >&2
echo "  Saved to: $(basename "$SESSIONS_DIR")/compaction-$TIMESTAMP.md" >&2
echo "  Branch: $BRANCH | Version: $VERSION" >&2
echo "  If you need prior context, read that file." >&2
echo "============================================" >&2
echo "" >&2

exit 0
